# Generated by Django 3.2.8 on 2021-10-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='E-mail')),
                ('department', models.CharField(blank=True, max_length=20, null=True, verbose_name='Department')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='Salary')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
